# Generated by Django 5.2.4 on 2025-07-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='closed',
            new_name='closed_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='open',
        ),
    ]
