# Generated by Django 5.2.4 on 2025-08-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='document_type',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('rg', 'RG'), ('cnh', 'CNH')], max_length=4, null=True),
        ),
    ]
